In [ ]:
print("hllo chuttya")

hllo chuttya


In [ ]:
### hello world 


In [ ]:
Print("hello world")

NameError: ignored

In [ ]:
print("Atharav Ravindra Patil")

Atharav Ravindra Patil


In [ ]:
print("from today there is new beginning")

from today there is new beginning


In [ ]:
input = ("enter your name")
input

'enter your name'

In [ ]:
x=5
type(x)

int

In [ ]:
y="rohit"
type(y)

str

In [ ]:
z=1,2
type(z)

tuple

In [ ]:
a=1.42
type(a)

float

In [ ]:
p= True
type(p)

bool

In [ ]:

name="rocky"
type(name)

str

In [ ]:
### datatypes

In [ ]:
Books=["Mast in python ","Bach in python"]
Books

['Mast in python ', 'Bach in python']

In [ ]:
### rules for naming variables 
### case sensitive 
### it should start with A-Z,a-z or _
### 

In [ ]:
Books_lists=["Mast in python ","Bach in python"]
Books_lists

['Mast in python ', 'Bach in python']

In [ ]:
Books+Lists=["Mast in python ","Bach in python"]
Books+Lists

SyntaxError: ignored

In [ ]:
Atharav=["stoks market gives too much loss,daily 500 profit is suffiecient going for mor than 2k leads too greediness which results in loss due to high expectations"]

In [ ]:
Atharav


['stoks market gives too much loss,daily 500 profit is suffiecient going for mor than 2k leads too greediness which results in loss due to high expectations']

In [ ]:
### Data Structures 
### List-> elements ar seperated by comma an enclosed with sqauare bracket 
### heterogenous
### List can be retrieved using index
# mutable- we an make the changes after creatung list

In [ ]:
Sample_list=[1,2,"hi",4,4,5,6,8]
Sample_list

[1, 2, 'hi', 4, 4, 5, 6, 8]

In [ ]:
Sample_list[2]

'hi'

In [ ]:
Sample_list[4]=69
Sample_list

[1, 2, 'hi', 4, 69, 5, 6, 8]

In [ ]:
type(Sample_list)

list

In [ ]:
Sample_List=[1,2.7,"hi",4,4,5,6,8,-1]
Sample_List

[1, 2.7, 'hi', 4, 4, 5, 6, 8, -1]

In [ ]:
type(Sample_List)

list

In [ ]:
Sample_List[8]

-1

In [ ]:
Sample_List[-2]

8

In [ ]:
print(Sample_List[-3:])


[6, 8, -1]


In [ ]:
###tuple
##heterogeneous
#paranthesis
#immutable

In [ ]:
Sample_tuple=(1,2.7,"hi",4,4,5,6,8,-1)
Sample_tuple

(1, 2.7, 'hi', 4, 4, 5, 6, 8, -1)

In [ ]:
Sample_tuple[1]

NameError: ignored

In [ ]:
Sample_tuple[2]=5

TypeError: ignored

In [ ]:
### Set
###doesnot allow duplicates
### in Set.elements cannot be retrived using index
# set is mutable

In [ ]:
sample_set=(1,2.7,"hi",5,9,54,6,8,-1,'app',0)
sample_set

(1, 2.7, 'hi', 5, 9, 54, 6, 8, -1, 'app', 0)

In [ ]:
sample_set.remove('app')
sample_set



AttributeError: ignored

In [ ]:
### dictionary 
## has key value pair data structure 
## values can be duplicated value can be retrieved using key 
### key cannnot be retrieved using value 


In [ ]:
Sample_dict={1:"apple",2:56.5,3:"yo",4:56.5,5:56.5,6:"string"}
Sample_dict

{1: 'apple', 2: 56.5, 3: 'yo', 4: 56.5, 5: 56.5, 6: 'string'}

In [ ]:
Sample_dict[5]=98
Sample_dict

{1: 'apple', 2: 56.5, 3: 'yo', 4: 56.5, 5: 98, 6: 'string', 99: 69}

In [ ]:
Sample_dict[10]="bussiness"
Sample_dict

{1: 'apple',
 2: 56.5,
 3: 'yo',
 4: 56.5,
 5: 98,
 6: 'string',
 99: 69,
 10: 'bussiness'}

In [ ]:
Sample_dict[99]=69  
Sample_dict

{1: 'apple',
 2: 56.5,
 3: 'yo',
 4: 56.5,
 5: 98,
 6: 'string',
 99: 69,
 10: 'bussiness'}

In [ ]:
#Numpy ; package for multiimnsional array

In [ ]:
import numpy as np

In [ ]:
np.arange(5,100,2)


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_list)
list_of_list


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.zeros((6,9,5),int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0,

In [ ]:
list_plot=[[244,45,5,7],[6,89,9,69],[100,98,675,58]]
sample_try=np.array(list_plot)
sample_try

array([[244,  45,   5,   7],
       [  6,  89,   9,  69],
       [100,  98, 675,  58]])

In [ ]:
np.arange(4,250,9)

array([  4,  13,  22,  31,  40,  49,  58,  67,  76,  85,  94, 103, 112,
       121, 130, 139, 148, 157, 166, 175, 184, 193, 202, 211, 220, 229,
       238, 247])

In [ ]:
np.ones(9,float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2) #uniform distribution

array([[0.39812378, 0.13783484],
       [0.19547841, 0.71669276],
       [0.83323613, 0.76206146]])

In [ ]:
np.random.randn(3,2) ## random distsribution

array([[ 0.23082548,  0.70328558],
       [ 0.89951885, -1.18967819],
       [-1.80525792, -0.4304055 ]])

In [ ]:
np.random.randint,(9,100)

(<function RandomState.randint>, (9, 100))

In [ ]:
np.random.randint(8,100,19)

array([95, 77, 99, 15, 62, 84, 21, 85, 41, 37, 68, 89, 42, 85, 18, 67, 35,
       67, 36])

In [ ]:
Sample_array=np.arange(30)
Sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(2,60,20)
rand_array

array([30, 32, 44,  5, 49, 59,  8, 15, 16, 12, 12, 58, 17, 27, 42, 53, 37,
       31,  6, 33])

In [ ]:
Sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
rand_array.min()  #minimum value

5

In [ ]:
rand_array.argmin()  

3

In [ ]:
mple_list=np.arange(100)
mple_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
mple_list.argmin()

0

In [ ]:
mple_list.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
rand_array.dtype

dtype('int64')

In [ ]:
rand_array


array([30, 32, 44,  5, 49, 59,  8, 15, 16, 12, 12, 58, 17, 27, 42, 53, 37,
       31,  6, 33])

In [ ]:
a=np.eye(3
        )
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.08058662, 0.41302457, 0.18800948],
       [0.57773972, 0.87281963, 0.2248221 ]])

In [ ]:
a.T

array([[0.08058662, 0.57773972],
       [0.41302457, 0.87281963],
       [0.18800948, 0.2248221 ]])

In [ ]:
arr_array=np.arange(11,25)

print("input=\n",arr_array)


input=
 [11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
arr_array[3]

14

In [ ]:
arr_array[3:7]

array([14, 15, 16, 17])

In [ ]:
arr_array[1:2
          ]=100
arr_array

array([ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24])

In [ ]:
subset_arr_array=arr_array[2:9]
subset_arr_array
print("valid numbers are:\n",subset_arr_array)

valid numbers are:
 [13 14 15 16 17 18 19]


In [ ]:
subset_arr_array[3:5]

array([16, 17])

In [ ]:
subset_arr_array[:]=101
subset_arr_array

array([101, 101, 101, 101, 101, 101, 101])

In [ ]:
#Two-Dimentional array

In [ ]:
import numpy as at

In [ ]:
sample_matrix=at.array([[30,20,4,34],[34,44,54,4],[43,54,23,2]])
sample_matrix

array([[30, 20,  4, 34],
       [34, 44, 54,  4],
       [43, 54, 23,  2]])

In [ ]:
sample_matrix[2][3]

2

In [ ]:
sample_matrix[:,2]        #row,columns

array([ 4, 54, 23])

In [ ]:
sample_matrix[1,2]

54

In [ ]:
sample_matrix[1][2:]

array([54,  4])

In [ ]:
sample_matrix[0:2,2]

array([ 4, 54])

In [ ]:
sample_ar=at.arange(1,20)
print("Your expected value is:",sample_ar)

Your expected value is: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
at.mean(sample_ar)
print("mean is:",at.mean)

mean is: <function mean at 0x7fdf74035790>


In [ ]:
at.var(sample_ar)

30.0

In [ ]:
at.mean(sample_ar)

10.0

In [ ]:
Sports=(["golf","cricket","football","basketball","baseball","vollyball","tt","tt"])
print("selected sports can be:\n",Sports)

selected sports can be:
 ['golf', 'cricket', 'football', 'basketball', 'baseball', 'vollyball', 'tt', 'tt']


In [ ]:
at.unique(Sports)

array(['baseball', 'basketball', 'cricket', 'football', 'golf', 'tt',
       'vollyball'], dtype='<U10')

In [ ]:
# pandas: to create data , create table ,manipulation

In [1]:
import pandas as pd

In [8]:
gf=pd.read_csv("student.csv")


In [9]:
gf.head()

id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [11]:
gf.head(10)

id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78    male
9  10     Big John   Four    55  female

In [12]:
gf.tail()

id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [13]:
gf.tail(25)

id         name  class  mark  gender
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [20]:
gf.sample(10)

id         name  class  mark  gender
2    3       Arnold  Three    55    male
26  27     Big Nose  Three    81  female
25  26       Crelea  Seven    79    male
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
6    7  My John Rob  Fifth    78    male
27  28    Rojj Base  Seven    86  female
5    6    Alex John   Four    55    male
16  17        Tumyu    Six    54    male
19  20       Jackly   Nine    65  female

In [21]:
gf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      35 non-null     int64 
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64 
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB


In [23]:
gf.shape

(35, 5)

In [24]:
gf.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [25]:
gf.isnull().sum()

id        0
name      0
class     0
mark      0
gender    0
dtype: int64

In [26]:
gf.describe

<bound method NDFrame.describe of     id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Ei

In [32]:
tt=pd.read_csv("health_effects.csv")

In [33]:
tt.head(8)

1                                  (+)-inotropic  \
0  2                               (-)-chronotropic   
1  3                                  (-)-inotropic   
2  4  11beta-hydroxysteroid-dehydrogenase inhibitor   
3  5                      12-lipoxygenase inhibitor   
4  6  17beta-hydroxysteroid-dehydrogenase inhibitor   
5  7                     5alpha-reductase inhibitor   
6  8       5-hydroxyeicosatetraenoic-acid inhibitor   
7  9                  5-hydroxytryptamine inhibitor   

  An agent that alters the force or energy of muscular contractions. Positively inotropic agents increase the strength of muscular contraction.  \
0  An agent that may change the heart rate by aff...                                                                                              
1  An agent that alters the force or energy of mu...                                                                                              
2                                                NaN                                                                                              
3                                                NaN                                                                                              
4                                                NaN                                                                                              
5                                                NaN                                                                                              
6                                                NaN                                                                                              
7                                                NaN                                                                                              

                                                NULL  
0                                                NaN  
1                                                NaN  
2  A compound or agent that combines with an enzy...  
3  A compound or agent that combines with an enzy...  
4  A compound or agent that combines with an enzy...  
5  An EC 1.3.1.* (oxidoreductase acting on CH-CH ...  
6  A substance that diminishes the rate of a chem...  
7  Drugs that bind to but do not activate seroton...

In [35]:
pf=pd.read_csv("GlobalLandTemperatures_GlobalTemperatures.csv")

In [36]:
pf.info

<bound method DataFrame.info of               dt  LandAverageTemperature  LandAverageTemperatureUncertainty  \
0     1750-01-01                   3.034                              3.574   
1     1750-02-01                   3.083                              3.702   
2     1750-03-01                   5.626                              3.076   
3     1750-04-01                   8.490                              2.451   
4     1750-05-01                  11.573                              2.072   
...          ...                     ...                                ...   
3187  2015-08-01                  14.755                              0.072   
3188  2015-09-01                  12.999                              0.079   
3189  2015-10-01                  10.801                              0.102   
3190  2015-11-01                   7.433                              0.119   
3191  2015-12-01                   5.518                              0.100   

      LandMaxTemper

In [40]:
pf.dtypes

dt                                            object
LandAverageTemperature                       float64
LandAverageTemperatureUncertainty            float64
LandMaxTemperature                           float64
LandMaxTemperatureUncertainty                float64
LandMinTemperature                           float64
LandMinTemperatureUncertainty                float64
LandAndOceanAverageTemperature               float64
LandAndOceanAverageTemperatureUncertainty    float64
dtype: object

In [43]:
tail=pf.tail(9)
print("result=",tail)

result=               dt  LandAverageTemperature  LandAverageTemperatureUncertainty  \
3183  2015-04-01                   9.313                              0.088   
3184  2015-05-01                  12.312                              0.081   
3185  2015-06-01                  14.505                              0.068   
3186  2015-07-01                  15.051                              0.086   
3187  2015-08-01                  14.755                              0.072   
3188  2015-09-01                  12.999                              0.079   
3189  2015-10-01                  10.801                              0.102   
3190  2015-11-01                   7.433                              0.119   
3191  2015-12-01                   5.518                              0.100   

      LandMaxTemperature  LandMaxTemperatureUncertainty  LandMinTemperature  \
3183              15.224                          0.137               3.402   
3184              18.181                   

In [44]:
pf.shape

(3192, 9)

In [47]:
avgtmp=pf.LandAndOceanAverageTemperature
print("average temperature:",avgtmp)

average temperature: 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
         ...  
3187    17.589
3188    17.049
3189    16.290
3190    15.252
3191    14.774
Name: LandAndOceanAverageTemperature, Length: 3192, dtype: float64


In [48]:
pf.size

28728

In [50]:
pf.isnull().sum()

dt                                              0
LandAverageTemperature                         12
LandAverageTemperatureUncertainty              12
LandMaxTemperature                           1200
LandMaxTemperatureUncertainty                1200
LandMinTemperature                           1200
LandMinTemperatureUncertainty                1200
LandAndOceanAverageTemperature               1200
LandAndOceanAverageTemperatureUncertainty    1200
dtype: int64

In [51]:
pf.isnull()

dt  LandAverageTemperature  LandAverageTemperatureUncertainty  \
0     False                   False                              False   
1     False                   False                              False   
2     False                   False                              False   
3     False                   False                              False   
4     False                   False                              False   
...     ...                     ...                                ...   
3187  False                   False                              False   
3188  False                   False                              False   
3189  False                   False                              False   
3190  False                   False                              False   
3191  False                   False                              False   

      LandMaxTemperature  LandMaxTemperatureUncertainty  LandMinTemperature  \
0                   True                           True                True   
1                   True                           True                True   
2                   True                           True                True   
3                   True                           True                True   
4                   True                           True                True   
...                  ...                            ...                 ...   
3187               False                          False               False   
3188               False                          False               False   
3189               False                          False               False   
3190               False                          False               False   
3191               False                          False               False   

      LandMinTemperatureUncertainty  LandAndOceanAverageTemperature  \
0                              True                            True   
1                              True                            True   
2                              True                            True   
3                              True                            True   
4                              True                            True   
...                             ...                             ...   
3187                          False                           False   
3188                          False                           False   
3189                          False                           False   
3190                          False                           False   
3191                          False                           False   

      LandAndOceanAverageTemperatureUncertainty  
0                                          True  
1                                          True  
2                                          True  
3                                          True  
4                                          True  
...                                         ...  
3187                                      False  
3188                                      False  
3189                                      False  
3190                                      False  
3191                                      False  

[3192 rows x 9 columns]

In [52]:
import numpy as np

In [56]:
labels=["w","x","y","z"]
sampl_list=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,"x":2,"y":3,"z":4}

In [ ]:
pd.Series(data=labels)

0    w
1    x
2    y
3    z
dtype: object

In [58]:
pd.Series(data=sampl_list)

0    100
1    200
2    300
3    400
dtype: int64

In [60]:
pd.Series(data=dict)

w    10
x     2
y     3
z     4
dtype: int64

In [59]:
pd.Series(data=array)

0    1
1    2
2    3
3    4
dtype: int64